import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Injectable()
export class CustomerService {
  getData() {
    return [
      {
        remite: 'HUDN',
        nombres: 'Laura Sofia',
        apellidos: 'Gomez Pabon',
        fecha_parto: '2025-04-10',
        no_doc: '123456789',
        edad: '25',
        telefono: '3111234567',
        barrio: 'La Rosa',
        direccion: 'Calle 123 #45-67',
        educacion_presencial: 'Si',
        fecha_llamada: '2025-04-11',
        llamada_entrante: true, 
        llamada_saliente: false, 
        responsable: 'Juan Perez',
        recibe_asesoria_si: true, 
        recibe_asesoria_no: false, 
        posible_donante_si: true, 
        posible_donante_no: false, 
        fecha_visita: '2025-04-12',
        observaciones: 'Ninguna',
      },
      {
        remite: 'HUDN',
        nombres: 'Laura Sofia',
        apellidos: 'Gomez Pabon',
        fecha_parto: '2025-04-10',
        no_doc: '123456789',
        edad: '25',
        telefono: '3111234567',
        barrio: 'La Rosa',
        direccion: 'Calle 123 #45-67',
        educacion_presencial: 'Si',
        fecha_llamada: '2025-04-11',
        llamada_entrante: true, 
        llamada_saliente: false, 
        responsable: 'Juan Perez',
        recibe_asesoria_si: true, 
        recibe_asesoria_no: false, 
        posible_donante_si: true, 
        posible_donante_no: false, 
        fecha_visita: '2025-04-12',
        observaciones: 'Ninguna',
      },
      {
        remite: 'HUDN',
        nombres: 'Laura Sofia',
        apellidos: 'Gomez Pabon',
        fecha_parto: '2025-04-10',
        no_doc: '123456789',
        edad: '25',
        telefono: '3111234567',
        barrio: 'La Rosa',
        direccion: 'Calle 123 #45-67',
        educacion_presencial: 'Si',
        fecha_llamada: '2025-04-11',
        llamada_entrante: true, 
        llamada_saliente: false, 
        responsable: 'Juan Perez',
        recibe_asesoria_si: true, 
        recibe_asesoria_no: false, 
        posible_donante_si: true, 
        posible_donante_no: false, 
        fecha_visita: '2025-04-12',
        observaciones: 'Ninguna',
      },
      {
        remite: 'HUDN',
        nombres: 'Laura Sofia',
        apellidos: 'Gomez Pabon',
        fecha_parto: '2025-04-10',
        no_doc: '123456789',
        edad: '25',
        telefono: '3111234567',
        barrio: 'La Rosa',
        direccion: 'Calle 123 #45-67',
        educacion_presencial: 'Si',
        fecha_llamada: '2025-04-11',
        llamada_entrante: true, 
        llamada_saliente: false, 
        responsable: 'Juan Perez',
        recibe_asesoria_si: true, 
        recibe_asesoria_no: false, 
        posible_donante_si: true, 
        posible_donante_no: false, 
        fecha_visita: '2025-04-12',
        observaciones: 'Ninguna',
      },
      {
        remite: 'HUDN',
        nombres: 'Laura Sofia',
        apellidos: 'Gomez Pabon',
        fecha_parto: '2025-04-10',
        no_doc: '123456789',
        edad: '25',
        telefono: '3111234567',
        barrio: 'La Rosa',
        direccion: 'Calle 123 #45-67',
        educacion_presencial: 'Si',
        fecha_llamada: '2025-04-11',
        llamada_entrante: true, 
        llamada_saliente: false, 
        responsable: 'Juan Perez',
        recibe_asesoria_si: true, 
        recibe_asesoria_no: false, 
        posible_donante_si: true, 
        posible_donante_no: false, 
        fecha_visita: '2025-04-12',
        observaciones: 'Ninguna',
      },
      {
        remite: 'HUDN',
        nombres: 'Laura Sofia',
        apellidos: 'Gomez Pabon',
        fecha_parto: '2025-04-10',
        no_doc: '123456789',
        edad: '25',
        telefono: '3111234567',
        barrio: 'La Rosa',
        direccion: 'Calle 123 #45-67',
        educacion_presencial: 'Si',
        fecha_llamada: '2025-04-11',
        llamada_entrante: true, 
        llamada_saliente: false, 
        responsable: 'Juan Perez',
        recibe_asesoria_si: true, 
        recibe_asesoria_no: false, 
        posible_donante_si: true, 
        posible_donante_no: false, 
        fecha_visita: '2025-04-12',
        observaciones: 'Ninguna',
      },
      {
        remite: 'HUDN',
        nombres: 'Laura Sofia',
        apellidos: 'Gomez Pabon',
        fecha_parto: '2025-04-10',
        no_doc: '123456789',
        edad: '25',
        telefono: '3111234567',
        barrio: 'La Rosa',
        direccion: 'Calle 123 #45-67',
        educacion_presencial: 'Si',
        fecha_llamada: '2025-04-11',
        llamada_entrante: true, 
        llamada_saliente: false, 
        responsable: 'Juan Perez',
        recibe_asesoria_si: true, 
        recibe_asesoria_no: false, 
        posible_donante_si: true, 
        posible_donante_no: false, 
        fecha_visita: '2025-04-12',
        observaciones: 'Ninguna',
      },
      {
        remite: 'HUDN',
        nombres: 'Laura Sofia',
        apellidos: 'Gomez Pabon',
        fecha_parto: '2025-04-10',
        no_doc: '123456789',
        edad: '25',
        telefono: '3111234567',
        barrio: 'La Rosa',
        direccion: 'Calle 123 #45-67',
        educacion_presencial: 'Si',
        fecha_llamada: '2025-04-11',
        llamada_entrante: true, 
        llamada_saliente: false, 
        responsable: 'Juan Perez',
        recibe_asesoria_si: true, 
        recibe_asesoria_no: false, 
        posible_donante_si: true, 
        posible_donante_no: false, 
        fecha_visita: '2025-04-12',
        observaciones: 'Ninguna',
      },
      {
        remite: 'HUDN',
        nombres: 'Laura Sofia',
        apellidos: 'Gomez Pabon',
        fecha_parto: '2025-04-10',
        no_doc: '123456789',
        edad: '25',
        telefono: '3111234567',
        barrio: 'La Rosa',
        direccion: 'Calle 123 #45-67',
        educacion_presencial: 'Si',
        fecha_llamada: '2025-04-11',
        llamada_entrante: true, 
        llamada_saliente: false, 
        responsable: 'Juan Perez',
        recibe_asesoria_si: true, 
        recibe_asesoria_no: false, 
        posible_donante_si: true, 
        posible_donante_no: false, 
        fecha_visita: '2025-04-12',
        observaciones: 'Ninguna',
      },
      {
        remite: 'HUDN',
        nombres: 'Laura Sofia',
        apellidos: 'Gomez Pabon',
        fecha_parto: '2025-04-10',
        no_doc: '123456789',
        edad: '25',
        telefono: '3111234567',
        barrio: 'La Rosa',
        direccion: 'Calle 123 #45-67',
        educacion_presencial: 'Si',
        fecha_llamada: '2025-04-11',
        llamada_entrante: true, 
        llamada_saliente: false, 
        responsable: 'Juan Perez',
        recibe_asesoria_si: true, 
        recibe_asesoria_no: false, 
        posible_donante_si: true, 
        posible_donante_no: false, 
        fecha_visita: '2025-04-12',
        observaciones: 'Ninguna',
      },
      {
        remite: 'HUDN',
        nombres: 'Laura Sofia',
        apellidos: 'Gomez Pabon',
        fecha_parto: '2025-04-10',
        no_doc: '123456789',
        edad: '25',
        telefono: '3111234567',
        barrio: 'La Rosa',
        direccion: 'Calle 123 #45-67',
        educacion_presencial: 'Si',
        fecha_llamada: '2025-04-11',
        llamada_entrante: true, 
        llamada_saliente: false, 
        responsable: 'Juan Perez',
        recibe_asesoria_si: true, 
        recibe_asesoria_no: false, 
        posible_donante_si: true, 
        posible_donante_no: false, 
        fecha_visita: '2025-04-12',
        observaciones: 'Ninguna',
      },
      {
        remite: 'HUDN',
        nombres: 'Laura Sofia',
        apellidos: 'Gomez Pabon',
        fecha_parto: '2025-04-10',
        no_doc: '123456789',
        edad: '25',
        telefono: '3111234567',
        barrio: 'La Rosa',
        direccion: 'Calle 123 #45-67',
        educacion_presencial: 'Si',
        fecha_llamada: '2025-04-11',
        llamada_entrante: true, 
        llamada_saliente: false, 
        responsable: 'Juan Perez',
        recibe_asesoria_si: true, 
        recibe_asesoria_no: false, 
        posible_donante_si: true, 
        posible_donante_no: false, 
        fecha_visita: '2025-04-12',
        observaciones: 'Ninguna',
      },
      {
        remite: 'HUDN',
        nombres: 'Laura Sofia',
        apellidos: 'Gomez Pabon',
        fecha_parto: '2025-04-10',
        no_doc: '123456789',
        edad: '25',
        telefono: '3111234567',
        barrio: 'La Rosa',
        direccion: 'Calle 123 #45-67',
        educacion_presencial: 'Si',
        fecha_llamada: '2025-04-11',
        llamada_entrante: true, 
        llamada_saliente: false, 
        responsable: 'Juan Perez',
        recibe_asesoria_si: true, 
        recibe_asesoria_no: false, 
        posible_donante_si: true, 
        posible_donante_no: false, 
        fecha_visita: '2025-04-12',
        observaciones: 'Ninguna',
      },
      // {
      //     id: 1001,
      //     name: 'Josephine Darakjy',
      //     country: {
      //         name: 'Egypt',
      //         code: 'eg'
      //     },
      //     company: 'Chanay, Jeffrey A Esq',
      //     date: '2019-02-09',
      //     status: 'proposal',
      //     verified: true,
      //     activity: 0,
      //     representative: {
      //         name: 'Amy Elsner',
      //         image: 'amyelsner.png'
      //     },
      //     balance: 82429
      // },
    ];
  }

  constructor(private http: HttpClient) {}

  getCustomersMini() {
    return Promise.resolve(this.getData().slice(0, 5));
  }

  getCustomersSmall() {
    return Promise.resolve(this.getData().slice(0, 10));
  }

  getCustomersMedium() {
    return Promise.resolve(this.getData().slice(0, 50));
  }

  getCustomersLarge() {
    return Promise.resolve(this.getData().slice(0, 200));
  }

  getCustomersXLarge() {
    return Promise.resolve(this.getData());
  }

  getCustomers(params?: any) {
    return this.http
      .get<any>('https://www.primefaces.org/data/customers', { params: params })
      .toPromise();
  }
}
